

name: Lambda CI/CD Pipeline with GitHub Actions

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**' # trigger on changes to lambda code
      - 'deploy/aws/lambda/**'

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: setup go
          uses: actions/setup-go@v2
          with:
            go-version: '1.21.12'

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.9.2  # Specify your Terraform version

        - name: Initialize Terraform
          run: terraform init deploy/aws/lambda/

        - name: Plan Terraform
          env:
          TF_VAR_gcp_apikey: ${{ secrets.TF_VAR_gcp_apikey }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform plan deploy/aws/lambda/

        - name: Apply Terraform
          env:
          TF_VAR_gcp_apikey: ${{ secrets.TF_VAR_gcp_apikey }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform apply -auto-approve deploy/aws/lambda/
     
